/*
Purpose:
- create reporting-ready views for customers and products
- consolidate key metrics and kpis for downstream analysis

1. Customer Report 
Metrics definition:
- total_orders: number of distinct orders placed by the customer
- total_sales: total revenue generated by the customer
- total_quantity: total units purchased
- total_products: number of distinct products purchased
- lifespan: number of months between first and last order
- recency: months since most recent order
- avg_order_value: average revenue per order
- avg_monthly_spend: average revenue generated per month of activity

*/

drop view if exists report_customers;
drop view if exists report_products;

create view report_customers as 
with base_query as (
select 
	 s.order_number, 
	 s.product_key, 
	 s.order_date,
	 s.sales_amount, 
	 s.quantity, 
	 c.customer_key, 
	 c.customer_number, 
	 concat(c.first_name, ' ', c.last_name) as customer_name, -- transform 
	 datediff(year, c.birthdate, getdate()) age
from sales as s
left join customers as c
	on c.customer_key = s.customer_key 
where order_date is not null
) -- aggregations 
, customer_aggregation as (
select 
	customer_key, 
	customer_number, 
	customer_name,
	age,
	count(distinct order_number) as total_orders,
	sum(sales_amount) as total_sales, 
	sum(quantity) as total_quantity, 
	count(distinct product_key) as total_products,
	max(order_date) as last_order_date,
	datediff(month, min(order_date), max(order_date)) as lifespan
from base_query
group by customer_key, customer_number, customer_name, age)

-- final results 
select 
	customer_key, 
	customer_number, 
	customer_name,
	age,
	case when age < 20 then 'Under 20' 
		 when age between 20 and 29 then '20-29'
		 when age between 30 and 39 then '30-39'
		 when age between 40 and 49 then '40-49'
		 else '50 and above' end as age_group,
	case when total_sales >= 5000 and lifespan >= 12 then 'VIP'
		 when total_sales <= 5000 and lifespan >= 12 then 'Regular'
		 else 'New' end as customer_segment,
	datediff(month, last_order_date, getdate()) as most_recent_order,
	total_orders,
	total_sales, 
	total_quantity,
	total_products,
	last_order_date,
	lifespan,
	-- AVO  average order value
	case when total_orders = 0 then 0
	else total_sales / total_orders end as avg_order_value,
	-- avg monthly spend
	case when lifespan = 0 then total_sales
	else total_sales / lifespan end as avg_monthly_spend 
from customer_aggregation;

/* ======================================================= */

/* 2. Product Report 
Metrics definition:
- total_orders: number of distinct orders containing the product
- total_sales: total revenue generated by the product
- total_quantity: total units sold
- total_customers: number of unique customers who purchased the product
- lifespan: number of months between first and last sale
- recency: months since most recent sale
- avg_order_value: average revenue per order containing the product
- avg_monthly_revenue: average revenue generated per month of activity */ 

create view report_products as
with base_query as (
    select
        s.order_number,
        s.product_key,
        s.order_date,
        s.sales_amount,
        s.quantity,
        p.product_number,
        p.product_name,
        p.category,
        p.subcategory,
        p.cost
    from sales as s
    left join products as p
        on p.product_key = s.product_key
    where s.order_date is not null
)
-- aggregations
, product_aggregation as (
    select
        product_key,
        product_number,
        product_name,
        category,
        subcategory,
        cost,
        count(distinct order_number) as total_orders,
        sum(sales_amount) as total_sales,
        sum(quantity) as total_quantity,
        max(order_date) as last_order_date,
        datediff(month, min(order_date), max(order_date)) as lifespan
    from base_query
    group by
        product_key,
        product_number,
        product_name,
        category,
        subcategory,
        cost
)
-- final results
select
    product_key,
    product_number,
    product_name,
    category,
    subcategory,
    cost,
    datediff(month, last_order_date, getdate()) as recency,
    total_orders,
    total_sales,
    total_quantity,
    lifespan,
    -- avo: average order value
    case when total_orders = 0 then 0
	else total_sales / total_orders
    end as avg_order_value,
    -- average monthly revenue
    case when lifespan = 0 then total_sales
    else total_sales / lifespan
    end as avg_monthly_revenue
from product_aggregation;



